language: node_js
node_js:
  - "0.10"
before_install:
  - sudo apt-get install libudev-dev libusb-1.0-0-dev libzmq3 libzmq3-dev
  - npm install -g grunt-cli
before_script:
  - cd node_modules/node-hid
  - git submodule update --init
  - npm install
  - cd ../../
notifications:
  email: false